ДЗ 1
ulaista/2024-2-VK-EDU-Frontend-U-Istamov pull request #1
Opened 2024-09-24 00:10 UTC by ulaista

# Домашнее задание №1

Прошу @martinkomitsky , @haseprogram , @kgrechin или @1marbur1 проверить его.

Что было сделано:
1) convertBytesToHuman: написано функция и наложена тест 
2) correctSentence: написано функция
3) nonUniqueElements: написано функция

2024-09-24 06:32 UTC, 1MarBur1 requested changes

2024-09-24 06:32 UTC, 1MarBur1 commented on homework1/convertBytesToHuman.js
> +  if (typeof bytes !== 'number' || bytes < 0 || isNaN(bytes) || !isFinite(bytes)) {
isFinite(NaN) возвращает false, поэтому можно сократить

2024-09-24 06:32 UTC, 1MarBur1 commented on homework1/correctSentence.js
> +  return correctedText;
отлично, но давай будем работать только со входной строкой, без создания новых? И вместо if используем тернарный оператор. 

Так же можно сократить запись получения последнего знака до correctedText.at(-1) :)

2024-09-24 06:32 UTC, 1MarBur1 commented on homework1/nonUniqueElements.js
> +    countMap[item] = (countMap[item] || 0) + 1;
все работает, тебе на вооружение:
это мы можем записать в виде
```
countMap[item] ??= 0
countMap[item]++
```
Такая запись присваивает 0 countMap[item] только если оно не имеет другого значения

2024-09-24 12:45 UTC, ulaista commented on homework1/convertBytesToHuman.js
> +  if (typeof bytes !== 'number' || bytes < 0 || isNaN(bytes) || !isFinite(bytes)) {
в приницпе да чеки проходят без него, забыл что было проверка в типах)

2024-09-24 13:26 UTC, ulaista commented on homework1/nonUniqueElements.js
> +    countMap[item] = (countMap[item] || 0) + 1;
спасибо!

2024-09-24 18:57 UTC, 1MarBur1 approved these changes
@martinkomitsky @HaseProgram @kgrechin approved

2024-09-25 20:47 UTC, HaseProgram approved these changes
12!

2024-09-25 20:47 UTC, merged