ДЗ 2
ulaista/2024-2-VK-EDU-Frontend-U-Istamov pull request #2
Opened 2024-09-30 23:04 UTC by ulaista

# Домашнее задание №2

Прошу @martinkomitsky , @haseprogram , @kgrechin или @1marbur1 проверить его.

Что было сделано:
1) Про инициализировано simple-chat из инструкции к дз
2) Построен DOM по аналогии телеграмм и сделано верстка под этот макет с использованием CSS метод Flexbox
3) Настроена в js логика приложение, сохранение сообщение в localstorage и отображение на экране, прокрутка при наборе

[ссылка на деплой сайта](https://ulaista.github.io/2024-2-VK-EDU-Frontend-U-Istamov/)

Фото отчет от проделанной работы:
<img width="562" alt="Screenshot 2024-09-30 at 06 03 41" src="https://github.com/user-attachments/assets/01ef52d8-8783-4571-8fd8-8a3062473527">
<img width="1416" alt="Screenshot 2024-09-30 at 06 03 53" src="https://github.com/user-attachments/assets/020d96ca-8e49-475f-a078-30918ef6178b">

2024-10-02 11:10 UTC, 1MarBur1 requested changes

2024-10-02 11:10 UTC, 1MarBur1 commented on simple-chat/src/index.html
скролл перекрывает контент, сделай padding

<img width="222" alt="Снимок экрана 2024-10-02 в 14 04 05" src="https://github.com/user-attachments/assets/e29a0d5b-ed11-4bb4-8e77-41fd49a238bd">

2024-10-02 11:10 UTC, 1MarBur1 commented on simple-chat/src/index.html
<img width="751" alt="Снимок экрана 2024-10-02 в 14 04 38" src="https://github.com/user-attachments/assets/ce97e076-9daa-4548-b00a-b356ae070e68">

давай закрепим время в правом нижнем углу сообщения? сейчас оно отображается сразу после текста сообщения

2024-10-02 11:10 UTC, 1MarBur1 commented on simple-chat/src/index.html
<img width="1145" alt="Снимок экрана 2024-10-02 в 14 07 26" src="https://github.com/user-attachments/assets/bb0c3af3-041b-4b6d-88c2-de5e47561fe8">

давай перевернем иконку файла как нужно)

2024-10-04 23:11 UTC, ulaista commented on simple-chat/src/index.html
все исправлено!

2024-10-06 11:28 UTC, 1MarBur1 commented on simple-chat/src/index.html
<img width="1138" alt="Снимок экрана 2024-10-06 в 14 26 30" src="https://github.com/user-attachments/assets/af5fe13e-6c70-4d14-b2d8-ba03488b99bb">

bg инпута заливается не полностью на декстопе, из-за чего сообщение в него "въезжает", на мобилке все гуд

2024-10-06 11:33 UTC, 1MarBur1 requested changes
bg инпута заливается не полностью на декстопе, из-за чего сообщение в него "въезжает", на мобилке все гуд

<img width="1138" alt="Снимок экрана 2024-10-06 в 14 26 30" src="https://github.com/user-attachments/assets/db28e25a-c935-4855-b328-0102b8ea473c">

В остальном все хорошо

2024-10-06 13:43 UTC, ulaista commented on simple-chat/src/index.html
Спасибо, подправил

2024-10-07 20:59 UTC, 1MarBur1 reviewed
В целом все хорошо - можно разбить стили/js по разным файлам, чтобы потом было проще переходить на React, но это можно сделать в след задании

@HaseProgram @martinkomitsky @kgrechin approved

2024-10-16 04:06 UTC, kgrechin approved these changes
@HaseProgram, @martinkomitsky аппрув

2024-10-22 12:49 UTC, 1MarBur1 approved these changes
@HaseProgram @martinkomitsky approved

2024-10-22 14:50 UTC, HaseProgram approved these changes
Ура, аппрув, 12!

2024-10-22 14:50 UTC, merged